name: Autobump

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    name: Check for new version
    runs-on: macos-latest
    steps:
      - uses: Homebrew/actions/setup-homebrew@main

      - name: Check for updates
        id: livecheck
        run: |
          json=$(brew livecheck --cask ${{ github.repository_owner }}/stretchly/stretchly --json)
          echo "outdated=$(echo "$json" | jq -r '.[0].version.outdated')" >> "$GITHUB_OUTPUT"
          echo "new_version=$(echo "$json" | jq -r '.[0].version.latest')" >> "$GITHUB_OUTPUT"

      - name: Bump cask PR
        if: steps.livecheck.outputs.outdated == 'true'
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          brew bump-cask-pr ${{ github.repository_owner }}/stretchly/stretchly \
            --version "${{ steps.livecheck.outputs.new_version }}" \
            --no-browse --no-fork
